// SPDX-License-Identifier: MIT
pragma solidity 0.8.19;
import {AutomationCompatibleInterface} from "@chainlink/src/v0.8/interfaces/AutomationCompatibleInterface.sol";
import {AutomationCompatible} from "@chainlink/src/v0.8/AutomationCompatible.sol";
import {IOrderManager} from "../order-manager/IOrderManager.sol";

contract Automatition is AutomationCompatibleInterface {
    // get manager interface
    IOrderManager private orderManager;

    /**
     * Use an interval in seconds and a timestamp to slow execution of Upkeep
     */
    uint public immutable interval;
    uint public lastTimeStamp;

    constructor(uint updateInterval) {
        interval = updateInterval;
        lastTimeStamp = block.timestamp;
    }

    function checkUpkeep(
        bytes calldata /* checkData */
    )
        external
        view
        override
        returns (bool upkeepNeeded, bytes memory /* performData */)
    {
        uint256[] memory _eligbleOrders = orderManager.getEligibleOrders();
        if (_eligbleOrders.length == 0) {
            upkeepNeeded = false;
            return (upkeepNeeded, "");
        }
        upkeepNeeded = true;
        return (upkeepNeeded, abi.encode(_eligbleOrders));
    }

    function performUpkeep(bytes calldata _performData) external override {
        //We highly recommend revalidating the upkeep in the performUpkeep function
        orderManager.executeOrders(abi.decode(_performData, (uint256[])));
        // We don't use the performData in this example. The performData is generated by the Automation Node's call to your checkUpkeep function
    }
}
