[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.20"

remappings = [
    "@chainlink/=node_modules/@chainlink/contracts/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@uniswap/v3-core/=node_modules/@uniswap/v3-core/",
    "@uniswap/v3-periphery/=node_modules/@uniswap/v3-periphery/",
    "forge-std/=node_modules/forge-std/src/",
    "ds-test/=node_modules/ds-test/src/",
]

[rpc_endpoints]
sepolia = "${GOERLI_RPC_URL}"
polygon = ""